services:
  mysql:
    image: mysql:8.4
    container_name: mysql_db
    restart: unless-stopped

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: cpu
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

  spring-boot-api:
    build: .
    container_name: spring_boot_api

    depends_on:
      - mysql

    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:mysql://mysql:3306/cpu?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: 8080

volumes:
  mysql_data: