spring.application.name=spring-boot

# ==========================================
# BASE DE DATOS
# ==========================================

spring.datasource.url=${DB_URL:jdbc:mysql://mysql:3306/cpu?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci}

spring.datasource.username=${DB_USERNAME:cpu_user}

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ==========================================
# SERVIDOR
# ==========================================

server.port=${PORT:8080}


# ==========================================
# CODIFICACIÓN
# ==========================================

server.servlet.encoding.charset=UTF-8

server.servlet.encoding.enabled=true

server.servlet.encoding.force=true